import { getCssText } from "$/stitches.config";
import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <style id="stitches">{getCssText()}</style>
      </head>
      <body>{children}</body>
    </html>
  );
}
