import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import TxtField from "~/components/Input";
import { css } from "@stitches/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className={styles.main}>
      <h1>Hi, world!</h1>
      <p>Welcome back to LongPathes!</p>
      <TxtField label="Yellow" type="text" />
    </main>
  );
}
